config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:create]
  root 'chatroom#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  post "message", to: "messages#create"

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {minimum:5, maximum:15},
            uniqueness: { case_sensitive: false }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error] = "You must be logged into perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

    def index
        @message = Message.new
        @messages = Message.all
    end

    def create
    
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(messages_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", 
                                        {foo: message_render(message),}

        end
    end

    private

    def messages_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :logged_in_redirect, only: [:new, :create]

    def new
    
    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Login Successfully!"
            redirect_to root_path
        else
            flash.new[:error] = "There was something wrong with your input..."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Logged out Successfully! To LoginPage"
        redirect_to login_path
    end

    private 

    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/_messages.html.erb
<% @messages.each do |message| %>
    <div class="event">
        <div class="content">
            <div class="summary">
            <a><%= message.user.username %></a>: <%= message.body%>
            </div>
        </div>
    </div>
<% end %>

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
    <i class="circular comments icon blue"></i>
    ChatRoom
  </h2>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
                <div class="content" id="messages">
                    <div class="header">Chat World</div>
                    <div class="meta">...recently...</div>
                    <div class="ui inverted divider"></div>
                    <div class="ui feed" id="message-container">
                            <%= render 'messages'%>
                    </div>
                </div>
                <div class="extra content">
                    <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
                        <div class="field">
                            <div class="ui fluid icon input">
                                <%= f.text_field :body %>
                                <%= f.button '<i class="bordered inverted blue send icon"></i>'.html_safe %>
                            </div>
                        </div>
                    <% end %>
                </div>           
        </div>
    </div>
    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
                <div class="content">
                    <div class="ui inverted vertical menu">
                        <a class="active item">
                        Online User
                        </a>
                        <a class="item">
                        Messages
                        </a>
                        <a class="item">
                        Friends
                        </a>
                    </div>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRChatapp</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render "shared/navigation" %>
    <div class="container-mainbody">
      <div class="ui container">
        <%=render 'shared/notifications'%>
        <%= yield %>
      </div>
    </div>
  </body>

</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
        <a><%= message.user.username %></a>: <%= message.body%>
        </div>
    </div>
</div>

app/views/shared/_navigation.html.erb
<div class="ui smaill inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item" %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: :delete,class: "item"%>
          <% else %>
            <%= link_to "Login", login_path, class: "item"%>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Login", login_path, class: "ui primary button"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_notifications.html.erb
<% flash.each do |message_type, message_content|%>
    <div class="ui <%= message_type%> message transition">
        <i class="close icon"></i>
        <div class="header">
        <%= message_content%>
        </div>
        
    </div>
<% end %>